### ISSUE TITLE
Does Logback follows semantic versioning?

### ISSUE THREAD

**Issue by sdelamo** [qos-ch/logback#704]
While updating from Logback 1.4.8 to 1.4.11, he [hit the removal of this deprecated method `ContextInitializer::configureByResource`](https://github.com/qos-ch/logback/commit/4b06e062488e4cb87f22be6ae96e4d7d6350ed6b). 

Does logback follow semantic versioning? Are breaking changes expected in patch releases?

**Comment by ceki** [comment]
@sdelamo  The deprecated method in question was removed because it was preventing the decoupling of logback initialization from JoranConfigurator.

Please note the `DefaultJoranConfigurator.configureByResource` method  is identical to `ContextInitializer.configureByResource` and can be used instead.
