### ISSUE TITLE
No Log starting from Version 1.5.5 using included file from resources of jar

### ISSUE THREAD

**Issue by coinzz** [qos-ch/logback#810]
1.5.4 is the last version where our log is still working. We have the following constellation:

Using an included logback from the resource folder of one of our own libraries. Our main project has the logback-spring.xml as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="logback-common.xml"/>
</configuration>
```
and the `logback-common.xml` file is found in the resource folder inside a jar file library that we build. 

I get the following logback log for all versions using the jar:
`15:58:49,768 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@1d9bec4d - URL [jar:file:/C:/Users/XX/.m2/repository/XX/XX/XX/XX/XX/XX.jar!/logback-common.xml] is not of type file`

When we customize our pom to work with the code locally without a jar file all logback versions have the following:
`16:01:08,532 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@1e5f4170 - Adding [file:/C:/Users/XX/AppData/Local/Workspaces/intellij/XX/XX/target/classes/logback-common.xml] to configuration watch list.`

In **both** cases 1.5.4 is able to print the application log, but starting from 1.5.5 no application log is produced anymore. Any ideas what changed starting from 1.5.5? Hope these information are enough at first.

**Comment by ceki** [comment]
In 1.3.x and until logback 1.5.4, Joran performed configuration using two distinct steps. It first read XML file (or files) and transformed it (or them) into an internal model. The model was processed separately using a processor which delegated processing to ModelHandlers. However, the ingestion of included XML files occurred in a much earlier step before the model was  processed.
 
 In logback 1.5.5 and later, the ingestion of included XML files occurs during model processing which allows for more coherent treatment of included files. For exact changes see commit af92be47a  fixing issue [LOGBACK-1746](https://jira.qos.ch/browse/LOGBACK-1746) as well as  [LOGBACK-1732](https://jira.qos.ch/browse/LOGBACK-1732), LOGBACK-1760 and LOGBACK-1746.
 
 In any case, the problem is most likely due to the Spring framework not having updated its code.

**Comment by ceki** [comment]
Related to https://github.com/spring-projects/spring-boot/issues/40491

**Comment by coinzz** [comment]
Ah yes thanks, we are using spring boot 3.2.x. Guess we will wait to use logback >= 1.5.5 after spring has fixed this issue :)

**Comment by coinzz** [comment]
Another question @ceki: Why is this "breaking change" not done in an at least minor or major patch level of logback?
