### ISSUE TITLE
 Issue with missing `class` attribute for `<evaluator>` after updating from Logback `1.5.12` to `1.5.13`+

### ISSUE THREAD

**Issue by vpikus** [qos-ch/logback#895]
After upgrading Logback from version `1.5.12` to `1.5.13` or higher, my application fails to initialize logging and throws an IllegalStateException during startup: 

```
java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.model.processor.EventEvaluatorModelHandler - Mandatory "class" attribute missing for <evaluator>
ERROR in ch.qos.logback.core.model.processor.EventEvaluatorModelHandler - No default classname could be found.
```

The error is related to the `<evaluator>` configuration in logback.xml:

```
<evaluator name="MY_EVAL">
        <expression>level &gt; DEBUG</expression>
</evaluator>
```

Is this the expected behavior? If so, are there any migration notes available?

**Comment by ceki** [comment]
In [version1.5.13](https://logback.qos.ch/news.html#1.5.13), the default evaluator for `EvaluatorFilter`, namely [JaninoEventEvaluator](https://logback.qos.ch/manual/filters.html#JaninoEventEvaluator)  was removed in order to prevent arbitrary code execution (ACE) attacks made possible by malicious configuration files. 

There is also [thresholdFilter](https://logback.qos.ch/manual/filters.html#thresholdFilter) which should be helpful.

See links in the text for more details.

**Comment by mathze** [comment]
hi @ceki,
I'm a little confused about the decision to remove the JaninoEventEvaluator. Wouldn't it be the same argument to also remove the Conditional(https://logback.qos.ch/manual/configuration.html#conditional)?
Not that I want it to be removed;). I just want to understand why evaluating code in conditional is ok but in JaninoEventEvaluator is not.
